### ISSUE TITLE
Episode 22 - LaraChat Live (March 2nd, 2017 5PM PST | Jason McCreary)

### ISSUE THREAD

**Issue by smayzes** [LaraChat/live#10]
**Hosts**

@mlantz
@ericvanjohnson
@smayzes
You?

**Guests**

@JasonMcCreary

**Topics**

**Comment by jasonmccreary** [comment]
@smayzes what's the medium for this episode? What time will it be?

**Comment by mlantz** [comment]
8pm EST and we use Google Hangouts so there is some video

**Comment by jasonmccreary** [comment]
8pm Friday night… Party time!

**Comment by ericvanjohnson** [comment]
This should be March 2nd, or are we changing the day?

**Comment by smayzes** [comment]
Hmm should always be on Thursdays unless we actually specify.

**Comment by jasonmccreary** [comment]
Thursday is preferred for me.

**Comment by ericvanjohnson** [comment]
Yes, it's Thursday, sorry about that confusion. March 2nd, not 3rd. Since you are in here @jasonmccreary and I didn't need to send my email reminder to you ( 👍 thanks for that BTW) we use issue trackers to discuss the upcoming show and give everyone a chance to submit questions here leading up to the show. If you have any topic ideas, feel free to drop them in here.

**Comment by ericvanjohnson** [comment]
Topics ideas to discuss for this show:

https://jason.pureconcepts.net/2017/01/shift-developer-platform/
https://laravelshift.com/convert-lumen-to-laravel
https://jason.pureconcepts.net/2017/01/pivoting-from-laravel-shift/ (Getting Git)

**Comment by jasonmccreary** [comment]
@smayzes @ericvanjohnson we're doing video as well right? Just curious as I may have to forgo the *Pillow Fort*.

**Comment by ericvanjohnson** [comment]
I for one was looking forward to the Pillow Fort but understand why you would not want to broadcast from your fortress of solitude. 

Yes, we stream video :-)

**Comment by jasonmccreary** [comment]
@ericvanjohnson I'm glad to set it up. Lighting just might be a bit dim 😉

**Comment by smayzes** [comment]
https://jason.pureconcepts.net/2016/11/getting-git-video-series/ 

- Team Pricing?

**Comment by jasonmccreary** [comment]
Sure thing.

For me, glad to touch on anything Shift - especially dig into the technical aspects - or, even better, how Shift has led me to pivot into other projects.

Also like to touch upon coaching and pairing with Laravel developers a la https://coaching.pureconcepts.net

**Comment by jasonmccreary** [comment]
For the show notes:

- Personalized Coaching Sessions with JMac - https://coaching.pureconcepts.net/
- YAGNI talk from Laracon 2016 - https://streamacon.com/video/laracon-us/jason-mccreary-yagni-with-laravel
- Full Stack Radio Episode with Kent Beck about "Emergent Design" - http://www.fullstackradio.com/16
- Or just find me on Twitter - [@gonedark](https://twitter.com/gonedark)
