### ISSUE TITLE
Episode 24 - LaraChat Live (April 13th, 2017 5PM PST | Jack McDade)

### ISSUE THREAD

**Issue by smayzes** [LaraChat/live#12]
**Hosts**

@mlantz
@ericvanjohnson
@smayzes
You?

**Guests**

@jackmcdade - Creator of Statamic (https://twitter.com/jackmcdade)

**Topics**

- Statamic migration to Laravel
- Amazing design work at statamic, Laravel, etc (Inspirations)
- http://jackmcdade.com/

Stream: https://youtu.be/UZuSpjZrlZA

**Comment by ericvanjohnson** [comment]
What drew your interest to Laravel? 
What was your motivation behind creating Statamic?

**Comment by smayzes** [comment]
* What made your decision to change Statamic version 2 to Laravel?
* Where do you get inspiration for your design style, it's very unique. 
* How did you get involved in the Laravel community?

**Comment by stevieg83** [comment]
What's your favourite whisky?
