### ISSUE TITLE
First Show Planning

### ISSUE THREAD

**Issue by smayzes** [LaraChat/live#2]
## Flow:
1. About the chat and why?
2. Guest Intro
   - Each guest talk a bit about themselves
3. Discussion Topics
## Suggested topics:
- Let's discuss

**Comment by mikebronner** [comment]
Possible topic: moving to development of drop-in packages, vs standalone projects (examples CMS, form, blog, etc.) as a critical move for the Laravel community, similar to how Django uses apps.

**Comment by alnutile** [comment]
@mikebronner makes sense. It helped a lot with my recent FeatureFlag research

**Comment by smayzes** [comment]
Jesse Schutt’s article here: http://zaengle.com/blog/diving-in-to-a-laravel-audit

I’d like to talk about the benefits of PHPMD and PHPCS.

**Comment by jschutt** [comment]
I'm no pro on PHPMD or PHPCS, but I found them to be very helpful in pointing out potential issues.

**Comment by alnutile** [comment]
Would it be more around our view of the article?
On Wed, Jan 27, 2016 at 1:28 PM Jesse Schutt <notifications@github.com>
wrote:

> I'm no pro on PHPMD or PHPCS, but I found them to be very helpful in
> pointing out potential issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LaraChat/live/issues/2#issuecomment-175783245>.
>
-- 
Alfred Nutile
--------------
DevelopersHangout Podcast
http://www.developershangout.io/
ReadOrListen Podcast
http://www.readorlisten.com/
About
https://alfrednutile.info/

**Comment by mikebronner** [comment]
I use PHPMD and PHPCS all the time. It makes me a better developer. It would be interesting discussing pros and cons of using something like PHPCS-Fixer (which I don't do, because I think its a crutch that does not improve your abilities).

**Comment by smayzes** [comment]
From my perspective, I use PHPCS and PHPMD as plugins to my IDE to help make sure the code is clean, readable, and consistent. 

But I would like to talk about some tips or perhaps a bit about what you guys know/think of cleancode, codesize, controversial, design, naming & unusedcode rules.

**Comment by phroggyy** [comment]
Talking about clean code, naming, and possibly even level of abstraction (which I find quite interesting to talk about, but can be expanded quite a bit...) I guess could be quite interesting

**Comment by mikebronner** [comment]
Another guest recommendation: Adam Engebretson
