### ISSUE TITLE
Episode 18 - LaraChat Live (January 5th, 2017)

### ISSUE THREAD

**Issue by smayzes** [LaraChat/live#5]
**Hosts**

@mlantz 
@ericvanjohnson
@smayzes
You?

**Guests**

@taylorotwell

**Topics**

- What practices do you employee to stay current with PHP, Laravel, Plugins, Patches? Best practices and challenges
- Plans and goals for the new year?
- ~What is Laravel Dusk?~

**Comment by ericvanjohnson** [comment]
Yell at him for not having LaraconUS in San Diego. Wait, that was my secret ulterior motive. You've seen nothing here. Move along.

**Comment by ericvanjohnson** [comment]
Ask Taylor about his decision to require PHP 7+ for Laravel 5.5

**Comment by rizqidjamaluddin** [comment]
I'll be in Hong Kong on that date so I won't be able to join, sadly. I would love to interrogate Taylor more about how he feels about the frontend world right now, if the Vue and Bootstrap inclusion-by-default in L5.3 is because he thinks those two have an edge the others don't, or if they just so happen to be popular. He gets a lot of questions about the backend, but rarely about the frontends that laravel drives.

**Comment by ericvanjohnson** [comment]
Sorry you are going to miss this @rizqidjamaluddin . Good topic ideas. If you come up with some specific questions just post them here.

**Comment by ericvanjohnson** [comment]
Other potential discussion items:

- Markdown Mail
- Laravel Mix
- Laravel Dusk testing suite

**Comment by ericvanjohnson** [comment]
Main topic for the roundtable discussion on this show will be `What practices do you employee to stay current with PHP, Laravel, Plugins, Patches? Best practices and challenges`

**Comment by mlantz** [comment]
With the 7.0 questions it may be worth inquiring to how Otwell feels about larger companies adopting the framework, Zend and Symfony have been working with this relationship for a few years now, is Laravel coming to that stage of development?

**Comment by smayzes** [comment]
> How do you get your comments shorter by 3 chars? Is it a stroke of luck everytime, or does it just happen to workout out that way? - @bmadigan

**Comment by sullyfischer** [comment]
What time is it going to be?

**Comment by ericvanjohnson** [comment]
@sullyfischer 5PM PST https://larachat.co/live

**Comment by ericvanjohnson** [comment]
Awesome show 
Youtube: https://youtu.be/tB2r7ImC4Xg 
Audio: http://podcast.larachat.co/18
