### ISSUE TITLE
Episode 20 - LaraChat Live (Feb 2nd, 2017 | Guest Eric Barnes)

### ISSUE THREAD

**Issue by smayzes** [LaraChat/live#8]
**Hosts**

@mlantz 
@ericvanjohnson
@smayzes
You?

**Guests**

@ericbarnes

**Topics**

**Comment by ericvanjohnson** [comment]
What inspired you to create Laravel News?

**Comment by mlantz** [comment]
Are you ever pressured into covering materials outside of the Laravel community?

**Comment by ericbarnes** [comment]
Here is some potential topic ideas: 

* Anything Laravel community related
* Marketing your packages 
* Running a side business with a full time job
* Working remote (been doing it for 5 years)
* Blogging, writing, etc. 
* Anything about Laravel News in general. 
* History of the framework. 

Or anything else really. Happy to answer any questions.

**Comment by ericvanjohnson** [comment]
I like the discussion point `Running a side business with a full-time job`. That seems to be a very common scenario in the community. Might want to make that the overarching topic of the show.

**Comment by mlantz** [comment]
This is something I am deeply interested in `Marketing your packages`

**Comment by smayzes** [comment]
My vote is on `Running a side business with a full-time job` as the primary topic. It affects all of us in this thread

**Comment by mlantz** [comment]
Its so true 😢

**Comment by actuallymab** [comment]
Completely agree with @ericvanjohnson and @smayzes I hope you will point out that.

**Comment by devcircus** [comment]
## 2 part question
1. What has been your crowning moment during your time with laravel news. When did the lightbulb turn on and you thought, you know, "we may be on to something". 
2. What are you personally working on to possibly release to the general public as a source of income, for you and of course, them. We know the idea is there. It's always there........
~devCircus
3rd of my 2 part question:
Suggestion: we need a book or video series. Turning a hacker into a tester. From Nonda to Zonda. How to take the common web developer and step their game up to Wathian style testing levels.

**Comment by ericvanjohnson** [comment]
Great show https://www.youtube.com/watch?v=0BtYSzkatVU
